"""add project_status enum

Revision ID: 7e4764677f65
Revises: c359feee38fe
Create Date: 2026-01-27 20:26:26.778168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4764677f65'
down_revision: Union[str, Sequence[str], None] = 'c359feee38fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    project_status_enum = sa.Enum(
        "idea",
        "planning",
        "in_progress",
        "paused",
        "finished",
        "archived",
        "published",
        "draft",
        name="project_status",
    )

    # Create enum type first
    project_status_enum.create(op.get_bind(), checkfirst=True)

    # Then add the column
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.Enum('idea', 'planning', 'in_progress', 'paused', 'finished', 'archived', 'published', 'draft', name='project_status'), server_default='idea', nullable=False), schema='portfolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status', schema='portfolio')
    # ### end Alembic commands ###

    project_status_enum = sa.Enum(
        "idea",
        "planning",
        "in_progress",
        "paused",
        "finished",
        "archived",
        "published",
        "draft",
        name="project_status",
    )

    # Drop enum type
    project_status_enum.drop(op.get_bind(), checkfirst=True)