"""initial schema

Revision ID: c359feee38fe
Revises:
Create Date: 2026-01-22 17:58:46.752286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c359feee38fe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "idea",
                "planning",
                "in_progress",
                "paused",
                "finished",
                "archived",
                "published",
                name="project_status",
            ),
            server_default="idea",
            nullable=False,
        ),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("deploy_date", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "status IN ('idea', 'planning', 'in_progress', 'paused', 'finished', 'archived', 'published')",
            name="status_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        schema="portfolio",
    )
    op.create_index(
        op.f("ix_portfolio_projects_id"),
        "projects",
        ["id"],
        unique=False,
        schema="portfolio",
    )
    op.create_table(
        "stacks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_normalized"),
        schema="portfolio",
    )
    op.create_table(
        "project_desc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), server_default="", nullable=False),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("full_desc", sa.Text(), nullable=True),
        sa.Column("lang", sa.Text(), server_default="pt", nullable=False),
        sa.CheckConstraint("lang IN ('pt', 'en', 'es')", name="lang_check"),
        sa.ForeignKeyConstraint(["id"], ["portfolio.projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "lang"),
        schema="portfolio",
    )
    op.create_table(
        "project_stack",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("stack_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["portfolio.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["stack_id"], ["portfolio.stacks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "stack_id"),
        schema="portfolio",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    raise RuntimeError("Downgrade not alloed for database initial migration")
    # ### end Alembic commands ###
